# Generated by Django 4.2.25 on 2025-12-03 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên danh mục')),
            ],
            options={
                'verbose_name_plural': 'Quản lý Danh mục',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tên sản phẩm')),
                ('price', models.IntegerField(verbose_name='Giá bán (VNĐ)')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Ảnh sản phẩm')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('is_hot', models.BooleanField(default=False, verbose_name='Hàng HOT 🔥')),
                ('is_new', models.BooleanField(default=True, verbose_name='Hàng Mới về 🆕')),
                ('active', models.BooleanField(default=True, verbose_name='Đang bán')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Danh mục')),
            ],
            options={
                'verbose_name_plural': 'Quản lý Sản phẩm',
            },
        ),
    ]
